openapi: 3.0.0
info:
  title: Social Network
  version: 1.0.0
  description: API для регистрации, аутентификации и управления профилем пользователя (пока)
servers:
  - url: http://localhost:8080
paths:
  /register:
    post:
      summary: Регистрация нового пользователя
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "http://localhost:8000/docs#/components/schemas/UserCreate"
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "http://localhost:8000/docs#/components/schemas/Profile"
        "400":
          description: Username already registered
  /login:
    post:
      summary: Вход пользователя
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "http://localhost:8000/docs#/components/schemas/UserLogin"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "http://localhost:8000/docs#/components/schemas/SessionResponse"
        "400":
          description: Invalid credentials
  /profile:
    get:
      summary: Получить профиль
      operationId: getProfile
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "http://localhost:8000/docs#/components/schemas/Profile"
        "404":
          description: User not found
    put:
      summary: Обновить профиль
      operationId: updateProfile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "http://localhost:8000/docs#/components/schemas/UserProfileUpdate"
      responses:
        "200":
          description: OK
        "401":
          description: Invalid or expired session
components:
  schemas:
    UserCreate:
      $ref: "http://localhost:8000/docs#/components/schemas/UserCreate"
    UserLogin:
      $ref: "http://localhost:8000/docs#/components/schemas/UserLogin"
    SessionResponse:
      $ref: "http://localhost:8000/docs#/components/schemas/SessionResponse"
    Profile:
      $ref: "http://localhost:8000/docs#/components/schemas/Profile"
    UserProfileUpdate:
      $ref: "http://localhost:8000/docs#/components/schemas/UserProfileUpdate"
