@startuml

skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor LightGray
    BorderColor Black
}

title ER-модель: Сервис постов и комментариев

entity "Посты (публикации)" as Publications {
    *id: UUID
    --
    user_id: UUID
    username: string
    content: string
    other_data: json
    created_at: datetime
    updated_at: datetime
}

entity "Комментарии" as Comments {
    *id: UUID
    --
    user_id: UUID
    publication_id: UUID
    username: string
    content: string
    other_data: json
    created_at: datetime
    updated_at: datetime
    status: string
}

entity "Теги пользователей" as Tags {
    *id: UUID
    --
    user_id_from: UUID
    user_id_to: UUID
    comment_id: UUID
    content: string
    description: string
    created_at: datetime
    updated_at: datetime
    post_cnt: int
}

Publications ||--|| Comments
Comments ||--|| Tags

@enduml
