@startuml

skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam class {
    BackgroundColor LightGray
    BorderColor Black
}

title ER-модель: Сервис пользователей

entity "Пользователи" as User {
    *id: UUID
    --
    username: string
    password: string
    phone: string
    email: string
}

entity "Профили" as Profile {
    *id: UUID
    --
    user_id: UUID
    first_name: string
    last_name: string
    bio: string
    date_of_birth: datetime
    avatar: string
    created_at: datetime
    updated_at: datetime
}

entity "Сессии" as Session {
    *id: UUID
    --
    user_id: UUID
    token: string
    created_at: datetime
    expires_at: datetime
}

User ||--|| Profile
User ||--|| Session

@enduml
